/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author alberto_angie
 */
public class ventanaJuego extends javax.swing.JFrame implements ActionListener{
    private int Contador;
    private String J1;
    private String J2;
    private int Cont;
    private boolean Enc;
    private boolean User;
    private boolean Ganador;
    private int Matriz[][];
    /**
     * Creates new form ventanaJuego
     */
    public ventanaJuego() {
        this.Matriz=new int[3][3];
        this.User=false;
        this.Enc=false;
        this.Ganador=false;
        this.Contador=0;
        this.Cont=0;
        initComponents();
        this.btn00.addActionListener(this);
        this.btn01.addActionListener(this);
        this.btn02.addActionListener(this);
        this.btn10.addActionListener(this);
        this.btn11.addActionListener(this);
        this.btn12.addActionListener(this);
        this.btn20.addActionListener(this);
        this.btn21.addActionListener(this);
        this.btn22.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        txtAgregar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblIniciar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mbnuevo = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn00.setBackground(new java.awt.Color(204, 204, 255));
        btn00.setForeground(new java.awt.Color(0, 153, 153));

        btn01.setBackground(new java.awt.Color(0, 255, 204));
        btn01.setForeground(new java.awt.Color(0, 153, 153));
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn02.setBackground(new java.awt.Color(204, 204, 255));
        btn02.setForeground(new java.awt.Color(0, 153, 153));

        btn10.setBackground(new java.awt.Color(0, 255, 204));
        btn10.setForeground(new java.awt.Color(0, 153, 153));

        btn11.setBackground(new java.awt.Color(204, 204, 255));
        btn11.setForeground(new java.awt.Color(0, 153, 153));

        btn12.setBackground(new java.awt.Color(0, 255, 204));
        btn12.setForeground(new java.awt.Color(0, 153, 153));

        btn20.setBackground(new java.awt.Color(204, 204, 255));
        btn20.setForeground(new java.awt.Color(0, 153, 153));

        btn21.setBackground(new java.awt.Color(0, 255, 204));
        btn21.setForeground(new java.awt.Color(0, 153, 153));

        btn22.setBackground(new java.awt.Color(204, 204, 255));
        btn22.setForeground(new java.awt.Color(0, 153, 153));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        Mbnuevo.setText("nuevo");
        jMenuBar1.add(Mbnuevo);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn00, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(btn01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn02, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(btn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar)))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addComponent(lblIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Contador++;
        if(Contador<=2){
            if(lblJugador1.getText()==""){
            J1=JOptionPane.showInputDialog("que letra desea usar X o 0 : ");
            if(J1.equals("x")|| J1.equals("X")){
                this.User=true;
            }
            lblJugador1.setText(txtAgregar.getText());
            txtAgregar.setText("");
            }else{
               
               lblJugador2.setText(txtAgregar.getText());
               lblIniciar.setText("Juego Iniciado");
               txtAgregar.setText(null);
               JOptionPane.showMessageDialog(null,"comienza la partida: " + lblJugador1.getText());
            }
        }else{
            JOptionPane.showMessageDialog(null,"jugadores Completos");
        }   
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaJuego().setVisible(true);
            }
        });
    }
    public void Limpiar(){
        this.btn00.setText(null);
        this.btn01.setText(null);
        this.btn02.setText(null);
        this.btn10.setText(null);
        this.btn11.setText(null);
        this.btn12.setText(null);
        this.btn20.setText(null);
        this.btn21.setText(null);
        this.btn22.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mbnuevo;
    int contador=0;
    int a,b;
    boolean reiniciando=false;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblIniciar;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JTextField txtAgregar;
    // End of variables declaration//GEN-END:variables
    
    @Override
    
    public void actionPerformed(ActionEvent e){
        if(Cont<9){
            if(e.getSource()==btn00){
                Cont++;
                //JOptionPane.showMessageDialog(null,"presionastes el 00");
                // el primer jugador usaralas x
                if(User){

                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[0][0]=1;
                            
                            btn00.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[0][0]=2;
                            btn00.setText("0");
                            break;
                        }
                         case 3:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                         case 4:{
                            this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }
                        case 5:{
                            this.Matriz[0][0]=1;         
                            btn00.setText("X");
                            break;
                        }
                          case 6:{
                            this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }
                           case 7:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                           case 8:{
                            this.Matriz[0][0]=2;   
                            btn00.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                       case 1:{
                           this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[0][0]=1; 
                            btn00.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[0][0]=2; 
                            btn00.setText("0");
                            break;
                        }

                    }
                }
            }



          if(e.getSource()==btn01){
              this.Matriz[0][1]=1;
                Cont++;
                //JOptionPane.showMessageDialog(null,Cont);
                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                         case 3:{
                             this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                         case 4:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                        case 5:{
                            btn01.setText("X");
                            this.Matriz[0][1]=1; 
                            break;
                        }
                        case 6:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                        case 8:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[0][1]=1; 
                            btn01.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[0][1]=2; 
                            btn01.setText("0");
                            break;
                        }

                    }
                }
            }
            if(e.getSource()==btn02){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 3:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 4:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 5:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 8:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[0][2]=1; 
                            btn02.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[0][2]=2; 
                            btn02.setText("0");
                            break;
                        }

                    }
                }
            }
            if(e.getSource()==btn10){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[1][0]=1; 
                            btn10.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[1][0]=2; 
                            btn10.setText("0");
                            break;
                        }
                         case 3:{
                            this.Matriz[1][0]=1; 
                            btn10.setText("X");
                            break;
                        }
                         case 4:{
                             this.Matriz[1][0]=2; 
                            btn10.setText("0");
                            break;
                        }
                          case 5:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                        case 8:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[1][0]=1;
                            btn10.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[1][0]=2;
                            btn10.setText("0");
                            break;
                        }

                    }
                }
            }
            if(e.getSource()==btn11){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                         case 3:{
                             this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                         case 4:{
                             this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                        case 5:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                           case 8:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[1][1]=1;
                            btn11.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[1][1]=2;
                            btn11.setText("0");
                            break;
                        }

                    }
                }
            }
                  if(e.getSource()==btn12){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                         case 3:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                         case 4:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                          case 5:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 8:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[1][2]=1;
                            btn12.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[1][2]=2;
                            btn12.setText("0");
                            break;
                        }

                    }
                }
            }
            if(e.getSource()==btn20){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 3:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                         case 4:{
                             this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 5:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 8:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[2][0]=1;
                            btn20.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[2][0]=2;
                            btn20.setText("0");
                            break;
                        }

                    }
                }
            }
            if(e.getSource()==btn21){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                         case 3:{
                             this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                         case 4:{
                             this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                        case 5:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                           case 8:{
                               this.Matriz[2][1]=2;
                            btn21.setText("0");
                        }

                        case 9:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                        case 3:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[2][1]=1;
                            btn21.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[2][1]=2;
                            btn21.setText("0");
                            break;
                        }

                    }
                }
            }
            if(e.getSource()==btn22){
                Cont++;

                // el primer jugador usaralas x
                if(User){
                    //el primer jugador usa la x
                    switch(Cont){
                        case 1:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 2:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                         case 3:{
                             this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                         case 4:{
                             this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                        case 5:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 6:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                        case 7:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 8:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }

                        case 9:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                    }
                }else{
                    switch(Cont){
                        case 1:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                        case 2:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 3:{this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                        case 4:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 5:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                        case 6:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 7:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }
                        case 8:{
                            this.Matriz[2][2]=1;
                            btn22.setText("X");
                            break;
                        }
                        case 9:{
                            this.Matriz[2][2]=2;
                            btn22.setText("0");
                            break;
                        }

                    }
                }
            }
            if(Matriz[0][0]==1&&Matriz[0][1]==1&&Matriz[0][2]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][0]==1&&Matriz[1][0]==1&&Matriz[2][0]==1){          
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[1][0]==1&&Matriz[1][1]==1&&Matriz[1][2]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[2][0]==1&&Matriz[2][1]==1&&Matriz[2][2]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][1]==1&&Matriz[1][1]==1&&Matriz[2][1]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][2]==1&&Matriz[1][2]==1&&Matriz[2][2]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][0]==1&&Matriz[1][1]==1&&Matriz[2][2]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[2][0]==1&&Matriz[1][1]==1&&Matriz[0][2]==1){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador1.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][0]==2&&Matriz[0][1]==2&&Matriz[0][2]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][0]==2&&Matriz[1][0]==2&&Matriz[2][0]==2){          
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[1][0]==2&&Matriz[1][1]==2&&Matriz[1][2]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[2][0]==2&&Matriz[2][1]==2&&Matriz[2][2]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][1]==2&&Matriz[1][1]==2&&Matriz[2][1]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][2]==2&&Matriz[1][2]==2&&Matriz[2][2]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[0][0]==2&&Matriz[1][1]==2&&Matriz[2][2]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
            if(Matriz[2][0]==2&&Matriz[1][1]==2&&Matriz[0][2]==2){
                JOptionPane.showMessageDialog(null,"Felicidades!!!.. Ganastes: " + lblJugador2.getText());
                Limpiar();
                Ganador=true;
            }
        }
        else{
           JOptionPane.showMessageDialog(null,"Juego Completo");
        }
        if(Cont==9 && !Ganador){
           JOptionPane.showMessageDialog(null,"Nadie Ganó :( !!! ");
           Limpiar();
        }
     
    }
}
